//
//  MockPlaylist.swift
//  Karamock
//
//  Created by A422GQ on 28/07/2026.
//
import SwiftUI

let mockPlaylist: [Playlist] = [
    Playlist(title: "Best Of Rock", gradientColors: [.red, .orange], songs: [
            Song(title: "Don't Stop Me Now", artist: "Queen", year: 1978, duration: "3:29", key: "F"),
            Song(title: "Sweet Child O' Mine", artist: "Guns N' Roses", year: 1987, duration: "5:56", key: "D"),
            Song(title: "Back In Black", artist: "AC/DC", year: 1980, duration: "4:15", key: "E"),
            Song(title: "Wonderwall", artist: "Oasis", year: 1995, duration: "4:18", key: "F#m"),
            Song(title: "Nothing Else Matters", artist: "Metallica", year: 1991, duration: "6:28", key: "Em"),
            Song(title: "Seven Nation Army", artist: "The White Stripes", year: 2003, duration: "3:52", key: "Em"),
            Song(title: "Livin' on a Prayer", artist: "Bon Jovi", year: 1986, duration: "4:09", key: "Dm"),
            Song(title: "Smoke on the Water", artist: "Deep Purple", year: 1972, duration: "5:40", key: "Gm"),
            Song(title: "Hotel California", artist: "Eagles", year: 1976, duration: "6:30", key: "Bm"),
            Song(title: "The Final Countdown", artist: "Europe", year: 1986, duration: "5:09", key: "F#m"),
            Song(title: "Highway to Hell", artist: "AC/DC", year: 1979, duration: "3:28", key: "A"),
            Song(title: "Bohemian Rhapsody", artist: "Queen", year: 1975, duration: "5:55", key: "Bb"),
            Song(title: "We Will Rock You", artist: "Queen", year: 1977, duration: "2:02", key: "Em"),
            Song(title: "We Are the Champions", artist: "Queen", year: 1977, duration: "2:59", key: "C"),
            Song(title: "Another One Bites the Dust", artist: "Queen", year: 1980, duration: "3:35", key: "Em"),
            Song(title: "Dream On", artist: "Aerosmith", year: 1973, duration: "4:27", key: "F#m"),
            Song(title: "Walk This Way", artist: "Aerosmith", year: 1975, duration: "3:40", key: "C#m"),
            Song(title: "Enter Sandman", artist: "Metallica", year: 1991, duration: "5:31", key: "E"),
            Song(title: "Master of Puppets", artist: "Metallica", year: 1986, duration: "8:35", key: "Em"),
            Song(title: "November Rain", artist: "Guns N' Roses", year: 1991, duration: "8:57", key: "C"),
            Song(title: "Paradise City", artist: "Guns N' Roses", year: 1987, duration: "6:46", key: "G"),
            Song(title: "Zombie", artist: "The Cranberries", year: 1994, duration: "5:06", key: "Em"),
            Song(title: "Creep", artist: "Radiohead", year: 1992, duration: "3:58", key: "G"),
            Song(title: "Under the Bridge", artist: "Red Hot Chili Peppers", year: 1991, duration: "4:24", key: "E"),
            Song(title: "Californication", artist: "Red Hot Chili Peppers", year: 1999, duration: "5:29", key: "Am"),
            Song(title: "Basket Case", artist: "Green Day", year: 1994, duration: "3:02", key: "E"),
            Song(title: "American Idiot", artist: "Green Day", year: 2004, duration: "2:54", key: "Ab"),
            Song(title: "Everlong", artist: "Foo Fighters", year: 1997, duration: "4:10", key: "D"),
            Song(title: "Learn to Fly", artist: "Foo Fighters", year: 1999, duration: "3:58", key: "B"),
            Song(title: "The Pretender", artist: "Foo Fighters", year: 2007, duration: "4:29", key: "Bm"),
            Song(title: "Bring Me to Life", artist: "Evanescence", year: 2003, duration: "3:56", key: "Em"),
            Song(title: "Numb", artist: "Linkin Park", year: 2003, duration: "3:07", key: "Fm"),
            Song(title: "In the End", artist: "Linkin Park", year: 2000, duration: "3:36", key: "Cm"),
            Song(title: "Smells Like Teen Spirit", artist: "Nirvana", year: 1991, duration: "5:01", key: "F"),
            Song(title: "Come As You Are", artist: "Nirvana", year: 1991, duration: "3:39", key: "Em"),
            Song(title: "Wind of Change", artist: "Scorpions", year: 1990, duration: "5:12", key: "C"),
            Song(title: "Rock You Like a Hurricane", artist: "Scorpions", year: 1984, duration: "4:13", key: "Em"),
            Song(title: "Eye of the Tiger", artist: "Survivor", year: 1982, duration: "4:05", key: "Cm"),
            Song(title: "Born to Be Wild", artist: "Steppenwolf", year: 1968, duration: "3:28", key: "E"),
            Song(title: "Paint It, Black", artist: "The Rolling Stones", year: 1966, duration: "3:22", key: "Em"),
            Song(title: "Start Me Up", artist: "The Rolling Stones", year: 1981, duration: "3:33", key: "C"),
            Song(title: "Roxanne", artist: "The Police", year: 1978, duration: "3:11", key: "Gm"),
            Song(title: "Message in a Bottle", artist: "The Police", year: 1979, duration: "4:49", key: "C#m"),
            Song(title: "The Boys Are Back in Town", artist: "Thin Lizzy", year: 1976, duration: "4:27", key: "D"),
            Song(title: "I Love Rock 'n' Roll", artist: "Joan Jett & the Blackhearts", year: 1981, duration: "2:55", key: "E"),
            Song(title: "Pour Some Sugar on Me", artist: "Def Leppard", year: 1987, duration: "4:27", key: "C#m"),
            Song(title: "Summer of '69", artist: "Bryan Adams", year: 1984, duration: "3:35", key: "D"),
            Song(title: "It's My Life", artist: "Bon Jovi", year: 2000, duration: "3:44", key: "Am"),
            Song(title: "Thunderstruck", artist: "AC/DC", year: 1990, duration: "4:52", key: "B"),
            Song(title: "Kashmir", artist: "Led Zeppelin", year: 1975, duration: "8:37", key: "D")
    ]),
    Playlist(title: "Années 2000\nen France", gradientColors: [.blue, .green], songs: [
            Song(title: "Jeune Demoiselle", artist: "Diam's", year: 2006, duration: "3:47", key: "Gm"),
            Song(title: "J'traine des pieds", artist: "Olivia Ruiz", year: 2005, duration: "3:36", key: "Am"),
            Song(title: "Le Vent Nous Portera", artist: "Noir Désir", year: 2001, duration: "4:44", key: "Bm"),
            Song(title: "Alors on danse", artist: "Stromae", year: 2009, duration: "3:26", key: "Cm"),
            Song(title: "Désenchantée", artist: "Kate Ryan", year: 2002, duration: "3:39", key: "F#m"),
            Song(title: "Confessions nocturnes", artist: "Diam's feat. Vitaa", year: 2006, duration: "4:12", key: "Dm"),
            Song(title: "Toi + Moi", artist: "Grégoire", year: 2008, duration: "3:05", key: "G"),
            Song(title: "Femme Like U", artist: "K.Maro", year: 2004, duration: "4:08", key: "Dm"),
            Song(title: "Ma Philosophie", artist: "Amel Bent", year: 2004, duration: "3:24", key: "Cm"),
            Song(title: "Et c'est parti...", artist: "Nadiya", year: 2004, duration: "3:32", key: "Bm"),
            Song(title: "Face à la mer", artist: "Calogero feat. Passi", year: 2004, duration: "3:41", key: "C#m"),
            Song(title: "Le Chemin", artist: "Kyo feat. Sita", year: 2003, duration: "3:29", key: "Bm"),
            Song(title: "Je saigne encore", artist: "Kyo", year: 2003, duration: "3:53", key: "Em"),
            Song(title: "Comme des enfants", artist: "Coeur de Pirate", year: 2008, duration: "2:51", key: "C"),
            Song(title: "J'aimerais tellement", artist: "Jena Lee", year: 2009, duration: "3:45", key: "Dm"),
            Song(title: "Tu trouveras", artist: "Natasha St-Pier", year: 2002, duration: "4:13", key: "A"),
            Song(title: "Mourir demain", artist: "Pascal Obispo et Natasha St-Pier", year: 2004, duration: "4:18", key: "F"),
            Song(title: "Sous le vent", artist: "Garou et Céline Dion", year: 2001, duration: "3:31", key: "G"),
            Song(title: "On s'attache", artist: "Christophe Maé", year: 2007, duration: "3:21", key: "Am"),
            Song(title: "Belle demoiselle", artist: "Christophe Maé", year: 2007, duration: "3:34", key: "Bm"),
            Song(title: "Parce qu'on vient de loin", artist: "Corneille", year: 2002, duration: "4:03", key: "Em"),
            Song(title: "En apesanteur", artist: "Calogero", year: 2002, duration: "3:27", key: "Dm"),
            Song(title: "Si seulement je pouvais lui manquer", artist: "Calogero", year: 2004, duration: "4:28", key: "C"),
            Song(title: "Double Je", artist: "Christophe Willem", year: 2007, duration: "3:22", key: "Gm"),
            Song(title: "Jacques a dit", artist: "Christophe Willem", year: 2007, duration: "3:45", key: "Cm"),
            Song(title: "New Soul", artist: "Yael Naim", year: 2007, duration: "3:45", key: "D"),
            Song(title: "La Lettre", artist: "Renan Luce", year: 2007, duration: "3:02", key: "A"),
            Song(title: "Le Dîner", artist: "Bénabar", year: 2005, duration: "3:13", key: "F"),
            Song(title: "Y'a une fille qu'habite chez moi", artist: "Bénabar", year: 2001, duration: "3:37", key: "C"),
            Song(title: "Qui de nous deux", artist: "-M-", year: 2003, duration: "4:04", key: "E"),
            Song(title: "Les Limites", artist: "Julien Doré", year: 2008, duration: "3:24", key: "Am"),
            Song(title: "Ta douleur", artist: "Camille", year: 2005, duration: "3:16", key: "Em"),
            Song(title: "Je suis un homme", artist: "Zazie", year: 2007, duration: "3:54", key: "Gm"),
            Song(title: "C'est une belle journée", artist: "Mylène Farmer", year: 2002, duration: "4:08", key: "Fm"),
            Song(title: "Q.I.", artist: "Mylène Farmer", year: 2005, duration: "4:22", key: "Em"),
            Song(title: "Désolé", artist: "Sexion d'Assaut", year: 2010, duration: "4:05", key: "Dm"),
            Song(title: "Wati by Night", artist: "Sexion d'Assaut", year: 2012, duration: "4:00", key: "Em"),
            Song(title: "Manhattan-Kaboul", artist: "Renaud et Axelle Red", year: 2002, duration: "3:45", key: "Am"),
            Song(title: "Je te promets", artist: "Zaho", year: 2008, duration: "3:54", key: "Em"),
            Song(title: "Dis-moi", artist: "BB Brunes", year: 2007, duration: "3:03", key: "D"),
            Song(title: "Lalalove You", artist: "BB Brunes", year: 2009, duration: "3:29", key: "Bm"),
            Song(title: "Le Manège", artist: "Jenifer", year: 2010, duration: "3:29", key: "Cm"),
            Song(title: "Tourner ma page", artist: "Jenifer", year: 2007, duration: "3:14", key: "A"),
            Song(title: "Au soleil", artist: "Jenifer", year: 2002, duration: "3:35", key: "D"),
            Song(title: "Donne-moi le temps", artist: "Jenifer", year: 2002, duration: "3:26", key: "C"),
            Song(title: "Écris l'histoire", artist: "Grégory Lemarchal", year: 2005, duration: "3:45", key: "Bm"),
            Song(title: "De temps en temps", artist: "Grégory Lemarchal", year: 2006, duration: "3:35", key: "G"),
            Song(title: "Nos mains", artist: "Yannick Noah", year: 2006, duration: "3:40", key: "F"),
            Song(title: "Te quiero", artist: "Stromae", year: 2009, duration: "3:29", key: "Dm"),
            Song(title: "House'llelujah", artist: "Stromae", year: 2009, duration: "3:23", key: "Em")
    ]),
    Playlist(title: "Karaoké\nClassics", gradientColors: [.yellow, .purple], songs: [
            Song(title: "I Will Survive", artist: "Gloria Gaynor", year: 1978, duration: "3:18", key: "Am"),
            Song(title: "Dancing Queen", artist: "ABBA", year: 1976, duration: "3:51", key: "A"),
            Song(title: "Take On Me", artist: "a-ha", year: 1984, duration: "3:46", key: "Bm"),
            Song(title: "Billie Jean", artist: "Michael Jackson", year: 1982, duration: "4:54", key: "F#m"),
            Song(title: "Rolling in the Deep", artist: "Adele", year: 2010, duration: "3:48", key: "Cm"),
            Song(title: "Uptown Funk", artist: "Mark Ronson feat. Bruno Mars", year: 2014, duration: "4:30", key: "Dm"),
            Song(title: "Like a Prayer", artist: "Madonna", year: 1989, duration: "5:41", key: "C"),
            Song(title: "Shallow", artist: "Lady Gaga & Bradley Cooper", year: 2018, duration: "3:37", key: "G"),
            Song(title: "Can't Stop the Feeling!", artist: "Justin Timberlake", year: 2016, duration: "3:56", key: "C"),
            Song(title: "Wake Me Up", artist: "Avicii", year: 2013, duration: "4:09", key: "Bm"),
            Song(title: "Someone Like You", artist: "Adele", year: 2011, duration: "4:45", key: "A"),
            Song(title: "Hello", artist: "Adele", year: 2015, duration: "4:55", key: "Fm"),
            Song(title: "Shake It Off", artist: "Taylor Swift", year: 2014, duration: "3:39", key: "G"),
            Song(title: "Blank Space", artist: "Taylor Swift", year: 2014, duration: "3:51", key: "F"),
            Song(title: "Firework", artist: "Katy Perry", year: 2010, duration: "3:48", key: "A"),
            Song(title: "Roar", artist: "Katy Perry", year: 2013, duration: "3:43", key: "Bb"),
            Song(title: "Toxic", artist: "Britney Spears", year: 2003, duration: "3:19", key: "Cm"),
            Song(title: "...Baby One More Time", artist: "Britney Spears", year: 1998, duration: "3:30", key: "Cm"),
            Song(title: "Shape of You", artist: "Ed Sheeran", year: 2017, duration: "3:53", key: "C#m"),
            Song(title: "Thinking Out Loud", artist: "Ed Sheeran", year: 2014, duration: "4:41", key: "D"),
            Song(title: "Happy", artist: "Pharrell Williams", year: 2013, duration: "3:53", key: "F"),
            Song(title: "Get Lucky", artist: "Daft Punk feat. Pharrell Williams", year: 2013, duration: "4:09", key: "F#m"),
            Song(title: "Can't Feel My Face", artist: "The Weeknd", year: 2015, duration: "3:35", key: "Am"),
            Song(title: "Blinding Lights", artist: "The Weeknd", year: 2019, duration: "3:20", key: "Fm"),
            Song(title: "Levitating", artist: "Dua Lipa", year: 2020, duration: "3:23", key: "Bm"),
            Song(title: "Flowers", artist: "Miley Cyrus", year: 2023, duration: "3:20", key: "G"),
            Song(title: "All of Me", artist: "John Legend", year: 2013, duration: "4:29", key: "Ab"),
            Song(title: "Stay With Me", artist: "Sam Smith", year: 2014, duration: "2:52", key: "C"),
            Song(title: "Bad Romance", artist: "Lady Gaga", year: 2009, duration: "4:54", key: "Am"),
            Song(title: "Poker Face", artist: "Lady Gaga", year: 2008, duration: "3:57", key: "Gm"),
            Song(title: "Halo", artist: "Beyoncé", year: 2008, duration: "4:21", key: "A"),
            Song(title: "Single Ladies (Put a Ring on It)", artist: "Beyoncé", year: 2008, duration: "3:13", key: "E"),
            Song(title: "Crazy in Love", artist: "Beyoncé feat. Jay-Z", year: 2003, duration: "3:56", key: "D"),
            Song(title: "Umbrella", artist: "Rihanna feat. Jay-Z", year: 2007, duration: "4:36", key: "Bb"),
            Song(title: "We Found Love", artist: "Rihanna feat. Calvin Harris", year: 2011, duration: "3:35", key: "F#m"),
            Song(title: "Since U Been Gone", artist: "Kelly Clarkson", year: 2004, duration: "3:09", key: "G"),
            Song(title: "Stronger (What Doesn't Kill You)", artist: "Kelly Clarkson", year: 2011, duration: "3:42", key: "A"),
            Song(title: "Chandelier", artist: "Sia", year: 2014, duration: "3:36", key: "Bb"),
            Song(title: "Cheap Thrills", artist: "Sia", year: 2016, duration: "3:31", key: "F#m"),
            Song(title: "Titanium", artist: "David Guetta feat. Sia", year: 2011, duration: "4:05", key: "C#m"),
            Song(title: "Señorita", artist: "Shawn Mendes & Camila Cabello", year: 2019, duration: "3:11", key: "Am"),
            Song(title: "Havana", artist: "Camila Cabello feat. Young Thug", year: 2017, duration: "3:36", key: "Gm"),
            Song(title: "Despacito", artist: "Luis Fonsi feat. Daddy Yankee", year: 2017, duration: "3:48", key: "Bm"),
            Song(title: "Dancing On My Own", artist: "Robyn", year: 2010, duration: "4:52", key: "F#m"),
            Song(title: "Don't Start Now", artist: "Dua Lipa", year: 2019, duration: "3:03", key: "Bm"),
            Song(title: "Price Tag", artist: "Jessie J feat. B.o.B", year: 2011, duration: "3:43", key: "F"),
            Song(title: "Rude", artist: "MAGIC!", year: 2013, duration: "3:45", key: "F"),
            Song(title: "Counting Stars", artist: "OneRepublic", year: 2013, duration: "4:17", key: "C#m"),
            Song(title: "Viva La Vida", artist: "Coldplay", year: 2008, duration: "4:02", key: "Ab"),
            Song(title: "A Sky Full of Stars", artist: "Coldplay", year: 2014, duration: "4:28", key: "F#m")
    ])
]
